# Generated by Django 5.2.4 on 2025-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('accent', 'accent'), ('info', 'info'), ('primary', 'primary')], default='info', max_length=20),
        ),
    ]
