# Generated by Django 5.2.4 on 2025-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(choices=[('book-open-text', 'book-open-text'), ('graduation-cap', 'graduation-cap'), ('briefcase', 'briefcase'), ('baby', 'baby')], default='briefcase', max_length=50),
        ),
    ]
