# Generated by Django 5.2.4 on 2025-07-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
